name: focusbadminton
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  #Get
  get: ^4.7.2

  #Google Sign In
  google_sign_in: ^6.3.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.8.0+1

  # UI & Design
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  image_picker: ^1.0.7

  # Navigation
  go_router: ^14.8.1

  # Local Storage
  hive: ^2.2.3
  shared_preferences: ^2.5.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

  # Splash Screen
  flutter_native_splash: ^2.4.4

  # Animations
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
