// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fH9Rk4t0JHo3ZjeFKMQubw2Egu-fQ0s',
    appId: '1:1062760484086:web:601631e701fd9d18f330d7',
    messagingSenderId: '1062760484086',
    projectId: 'focusbadminton',
    authDomain: 'focusbadminton.firebaseapp.com',
    storageBucket: 'focusbadminton.firebasestorage.app',
    measurementId: 'G-28DRGG000M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysbNzU4V-w992WJlnbbQO7DkSfx66KzE',
    appId: '1:1062760484086:android:ba4b0b8c1f3c4676f330d7',
    messagingSenderId: '1062760484086',
    projectId: 'focusbadminton',
    storageBucket: 'focusbadminton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVEy_3WFZVi0Krnn-F4uJp5rCrbA8_o8',
    appId: '1:1062760484086:ios:3620641c5264c4e1f330d7',
    messagingSenderId: '1062760484086',
    projectId: 'focusbadminton',
    storageBucket: 'focusbadminton.firebasestorage.app',
    iosBundleId: 'com.example.focusbadminton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKVEy_3WFZVi0Krnn-F4uJp5rCrbA8_o8',
    appId: '1:1062760484086:ios:3620641c5264c4e1f330d7',
    messagingSenderId: '1062760484086',
    projectId: 'focusbadminton',
    storageBucket: 'focusbadminton.firebasestorage.app',
    iosBundleId: 'com.example.focusbadminton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fH9Rk4t0JHo3ZjeFKMQubw2Egu-fQ0s',
    appId: '1:1062760484086:web:75632a766069a141f330d7',
    messagingSenderId: '1062760484086',
    projectId: 'focusbadminton',
    authDomain: 'focusbadminton.firebaseapp.com',
    storageBucket: 'focusbadminton.firebasestorage.app',
    measurementId: 'G-9B8E0XMSYD',
  );
}
